/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PrivateLiftResponseModel } from '../../models/private-lift-response-model';

export interface GetPrivateLiftsByOperatorId$Params {
  operatorId: string;
}

export function getPrivateLiftsByOperatorId(http: HttpClient, rootUrl: string, params: GetPrivateLiftsByOperatorId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PrivateLiftResponseModel>>> {
  const rb = new RequestBuilder(rootUrl, getPrivateLiftsByOperatorId.PATH, 'get');
  if (params) {
    rb.path('operatorId', params.operatorId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PrivateLiftResponseModel>>;
    })
  );
}

getPrivateLiftsByOperatorId.PATH = '/private-lifts/{operatorId}';
