version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    labels:
      kompose.service.type: ClusterIP
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  keycloak:
    container_name: snow-peak-keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: preview
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    command:
      - "start-dev"
      - "--import-realm"
    depends_on:
      - keycloak-postgres
    networks:
      - keycloak-network

  keycloak-postgres:
    container_name: keycloak-postgres
    image: postgres:15
    ports:
      - "5464:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5454:5432'

volumes:
  rabbitmq_data:
  rabbitmq_logs:
  postgres_data:
    driver: local

networks:
  keycloak-network:
    driver: bridge
