version: '3.8'

services:
  ski-lift-1:
    image: krisztianszenasi/ski-lift:latest
    stdin_open: true
    tty: true
    environment:
      LIFT_ID: lift1
      RABBITMQ_HOST: rabbitmq

  ski-lift-2:
    image: krisztianszenasi/ski-lift:latest
    stdin_open: true
    tty: true
    environment:
      LIFT_ID: lift2
      RABBITMQ_HOST: rabbitmq

  backend:
    image: backend-v1
    container_name: backend
    build: 
      context: ./backend
      args:
        - SPRING_BOOT_PORT:${SPRING_BOOT_PORT}
        - AMQP_PORT:${AMQP_PORT}
    restart: unless-stopped
    ports:
      - ${SPRING_BOOT_PORT}:${SPRING_BOOT_PORT}
      - ${AMQP_PORT}:${AMQP_PORT}
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - ${SPRING_BOOT_PORT}
      - ${AMQP_PORT}

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management UI
      - "15674:15674"  # WebSocket port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    labels:
      kompose.service.type: ClusterIP
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  keycloak:
    container_name: snow-peak-keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: preview
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    command:
      - "start-dev"
      - "--import-realm"
    depends_on:
      - keycloak-postgres
    networks:
      - keycloak-network

  keycloak-postgres:
    container_name: keycloak-postgres
    image: postgres:15
    ports:
      - "5464:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5454:5432'

volumes:
  rabbitmq_data:
  rabbitmq_logs:
  postgres_data:
    driver: local

networks:
  keycloak-network:
    driver: bridge
