# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest

---
# rabbitmq-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15674
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: rabbitmq-config
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-logs
          mountPath: /var/log/rabbitmq
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-data-pvc
      - name: rabbitmq-logs
        persistentVolumeClaim:
          claimName: rabbitmq-logs-pvc

---
# rabbitmq-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
  - name: websocket
    port: 15674
    targetPort: 15674
  selector:
    app: rabbitmq

---
# rabbitmq-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# ski-lift-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ski-lift-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ski-lift-1
  template:
    metadata:
      labels:
        app: ski-lift-1
    spec:
      containers:
      - name: ski-lift
        image: krisztianszenasi/ski-lift:latest
        env:
        - name: LIFT_ID
          value: "lift1"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ski-lift-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ski-lift-2
  template:
    metadata:
      labels:
        app: ski-lift-2
    spec:
      containers:
      - name: ski-lift
        image: krisztianszenasi/ski-lift:latest
        env:
        - name: LIFT_ID
          value: "lift2"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
