/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LiftResponseModel {
  endElevation?: number;
  endLatitude?: number;
  endLongitude?: number;
  extId?: string;
  id?: string;
  numberOfSeats?: number;
  seatCapacity?: number;
  startElevation?: number;
  startLatitude?: number;
  startLongitude?: number;
}
