/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LogResponseModel {
  id?: string;
  liftId?: string;
  payload?: string;
  time?: string;
}
