server:
    port: 8080

api:
    version: v1
    description: SnowPeak endpoints

spring:
    application:
        name: snow-peak-server
    flyway:
        enabled: true
        locations: classpath:db.migration
        default-schema: postgres
    datasource:
        url: jdbc:postgresql://localhost:5454/postgres
        username: postgres
        password: postgres
        hikari:
            connection-timeout: 60000
            idle-timeout: 60000
            maximum-pool-size: 5
            schema: postgres
    jpa:
        show-sql: true
        format-sql: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9090/realms/snow-peak

keycloak:
    realm: snow-peak
    resource: snow-peak
    auth-server-url: http://localhost:9090/auth
    ssl-required: external
    public-client: true
    use-resource-role-mappings: true

springdoc:
    enable-native-support: true
    default-produces-media-type: application/json
    enable-data-rest: false
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: method
        display-operation-id: true
        use-root-path: true
        filter: true