/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getLifts } from '../fn/lift-controller/get-lifts';
import { GetLifts$Params } from '../fn/lift-controller/get-lifts';
import { LiftResponseModel } from '../models/lift-response-model';

@Injectable({ providedIn: 'root' })
export class LiftControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getLifts()` */
  static readonly GetLiftsPath = '/lifts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLifts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLifts$Response(params?: GetLifts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LiftResponseModel>>> {
    return getLifts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLifts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLifts(params?: GetLifts$Params, context?: HttpContext): Observable<Array<LiftResponseModel>> {
    return this.getLifts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LiftResponseModel>>): Array<LiftResponseModel> => r.body)
    );
  }

}
